artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/chest_xray
  test_dir: artifacts/chest_xray/test
  train_dir: artifacts/chest_xray/train
  val_dir: artifacts/chest_xray/val

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_update.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5 

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

evaluation:
  root_dir: artifacts/evaluation
  metric_file_name: artifacts/evaluation/scores.json
  artifact_uri : artifacts/evaluation/mlflow_artifacts
  mlflow_experiment: artifacts/evaluation/mlflow_experiment

production:
  root_dir: artifacts/model_prod
  prod_model_path: artifacts/model_prod