artifacts_root: artifacts

data_model:
  root_dir: artifacts/chest_xray
  test_dir: artifacts/chest_xray/test
  train_dir: artifacts/chest_xray/train
  val_dir: artifacts/val

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_update.h5